<h1>Registration</h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('auth/default', array('controller' => 'registration', 'action' => 'index')));
$form->prepare();

echo $this->form()->openTag($form);
echo '<div class="form-group">';
echo $this->formRow($form->get('userName'));
echo '</div>';
echo '<div class="form-group">';
echo $this->formRow($form->get('userEmail'));
echo '</div>';
echo '<div class="form-group">';
echo $this->formRow($form->get('userPassword'));
echo '</div>';
echo '<div class="form-group">';
echo $this->formRow($form->get('userPasswordConfirm'));
echo '</div>';
// echo '<div class="form-group">';
// echo $this->formRow($form->get('captcha'));
// echo '</div>';
echo '<div class="form-group">';
echo $this->formSubmit($form->get('submit'));
echo '</div>';
echo $this->form()->closeTag();
?>